//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugNET_MVC.Resources.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrator has disabled anonymous access, please register or log in to view projects..
        /// </summary>
        public static string AnonymousAccessDisabled {
            get {
                return ResourceManager.GetString("AnonymousAccessDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to me.
        /// </summary>
        public static string AssignedToUser {
            get {
                return ResourceManager.GetString("AssignedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Recently.
        /// </summary>
        public static string CreatedRecently {
            get {
                return ResourceManager.GetString("CreatedRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed By.
        /// </summary>
        public static string ManagedBy {
            get {
                return ResourceManager.GetString("ManagedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next milestone due - {0}.
        /// </summary>
        public static string NextMilestoneDue {
            get {
                return ResourceManager.GetString("NextMilestoneDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Font color=&apos;red&apos;&gt;Warning:&lt;/font&gt; No Project Statuses are set to Closed.
        /// </summary>
        public static string NoClosedStatus {
            get {
                return ResourceManager.GetString("NoClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font color=&apos;red&apos;&gt;No due dates set.&lt;/font&gt;.
        /// </summary>
        public static string NoDueDatesSet {
            get {
                return ResourceManager.GetString("NoDueDatesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no projects configured for BugNET. We suggest the following to get started:.
        /// </summary>
        public static string NoProjects {
            get {
                return ResourceManager.GetString("NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no projects for you to view..
        /// </summary>
        public static string NoProjectsToViewMessage {
            get {
                return ResourceManager.GetString("NoProjectsToViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font color=&apos;red&apos;&gt;Warning:&lt;/font&gt; No Statuses set on project..
        /// </summary>
        public static string NoStatusSet {
            get {
                return ResourceManager.GetString("NoStatusSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} open issues.
        /// </summary>
        public static string OpenIssuesCount {
            get {
                return ResourceManager.GetString("OpenIssuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login to view projects on this site..
        /// </summary>
        public static string RegisterAndLoginMessage {
            get {
                return ResourceManager.GetString("RegisterAndLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new project.
        /// </summary>
        public static string Step1_LinkText {
            get {
                return ResourceManager.GetString("Step1_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a.
        /// </summary>
        public static string Step1_MessageFormat {
            get {
                return ResourceManager.GetString("Step1_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authentication settings.
        /// </summary>
        public static string Step2_LinkText {
            get {
                return ResourceManager.GetString("Step2_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your.
        /// </summary>
        public static string Step2_MessageFormat {
            get {
                return ResourceManager.GetString("Step2_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email settings.
        /// </summary>
        public static string Step3_LinkText {
            get {
                return ResourceManager.GetString("Step3_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your.
        /// </summary>
        public static string Step3_MessageFormat {
            get {
                return ResourceManager.GetString("Step3_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Recently.
        /// </summary>
        public static string UpdatedRecently {
            get {
                return ResourceManager.GetString("UpdatedRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to BugNET!.
        /// </summary>
        public static string WelcomeMessageHeader {
            get {
                return ResourceManager.GetString("WelcomeMessageHeader", resourceCulture);
            }
        }
    }
}
